name: 'Test new beta'
on:
  - pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: IvanovIvanov2/labeler@v5.0.0-alpha.1
      
      - uses: IvanovIvanov2/labeler@4f052778de9a9b80cb16cfb9079b02287285a4cb
      
      - uses: IvanovIvanov2/labeler@v5.0.0-beta
      

