name: Test python
on:
  workflow_dispatch:

jobs:
  setup-python:
    name: Setup
    runs-on: macos-11
    steps:      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.0
